name: Deploy Static Website to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to Azure Blob Storage ($web)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --destination \$web \
            --account-name i33amweb \
            --source . \
            --auth-mode key \
            --overwrite
